#!/bin/bash

# if type of change is not specified, quit
if [[ "$1" != "inc" && "$1" != "dec" ]]; then
    exit
fi

# if change in brightness is not passed, quit
[ -z "$2" ] && exit

# if change in brightness is not change in brightness, quit
regex='^\d+$'

if ! [[ "$( echo "$2" | grep -P "$regex" )" ]]; then
    exit
fi

max_brightness="$( cat /sys/class/backlight/intel_backlight/max_brightness )"
current_brightness="$( cat /sys/class/backlight/intel_backlight/brightness )"

step="$( echo "$max_brightness"'/100*'"$2" | bc )"

if [[ "$1" = "inc" ]]; then
    new_brightness="$( echo "$current_brightness+$step" | bc )"

    if (( new_brightness > max_brightness )); then
        new_brightness="$max_brightness"
    fi
else
    new_brightness="$( echo "$current_brightness-$step" | bc )"

    if (( new_brightness < 0 )); then
        new_brightness="0"
    fi
fi

echo "$new_brightness" > /sys/class/backlight/intel_backlight/brightness

msg_id="999998"
dunstify -a "Brightness" -u low -r "$msg_id" "$( /home/yog/bin/make_progress_bar "$new_brightness" "$max_brightness" "⚫" "⚪" )"

