#!/bin/bash

# Script to easily install stuff
# Usage: i <list of packages to install>
#   options: -p,--pacman <package>: treat the package followed by the flag as a pacman package
#            -a,--aur <package>: treat the package followed by the flag as an aur package

# bash: exit code 0: cool, great [ not false ]
# hence, the weird syntax with !

isInstalled() {
    pacman -Qi "$1" &>/dev/null
    echo $?
}

onPacman() {
    pacman -Si "$1" &>/dev/null
    echo $?
}

onAUR() {
    yay -Si "$1" &>/dev/null
    echo $?
}

pacman_packages=()
aur_packages=()

while (( $# > 0 )); do
    arg="$1"

    case "$arg" in
        -p|--pacman )
            shift
            if (( $(isInstalled "$1") )); then
                pacman_packages+=("$1")
            else
                echo "$1 is already installed"
            fi
            shift
            ;;
        -a|--aur )
            shift
            if (( $(isInstalled "$1") )); then
                aur_packages+=("$1")
            else
                echo "$1 is already installed"
            fi
            shift
            ;;
        * )
            if (( $(isInstalled "$1") )); then
                if (( ! $(onPacman "$1") )); then
                    pacman_packages+=("$1")
                elif (( ! $(onAUR "$1") )); then
                    aur_packages+=("$1")
                else
                    (>&2 echo Package "$1 not found")
                fi
            else
                echo "$1 is already installed"
            fi
            shift
            ;;
    esac
done

if (( ${#pacman_packages[@]} > 0 )); then
    sudo pacman -S "${pacman_packages[@]}"
fi


if (( ${#aur_packages[@]} > 0 )); then
    yay -S "${aur_packages[@]}"
fi

