#!/bin/bash

if [ ! -d ~/.scr ]; then
    mkdir ~/.scr
fi

maim ~/.scr/lock.png

mogrify -blur 0x16 -gravity center -undercolor white -pointsize 50 -fill black -annotate 0x0+0+150 "Locked at $( date '+%H%M' -d now )" ~/.scr/lock.png 

i3lock -i ~/.scr/lock.png
