#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    sys.exit(3)

f = sys.argv[1]

try:
    _f = open(f)
    _f.read(1024 * 1024)
    _f.close()
except UnicodeDecodeError:
    sys.exit(1)
except FileNotFoundError:
    sys.exit(2)
