#!/bin/bash

# wait for adapter status to update
sleep 1

adapter_status="$( acpi -a | awk -F': ' '{ print $2 }' )"

function powersave {
    # run at 60Hz
    swaymsg output eDP-1 mode '1920x1200@60.003Hz'

    # power saving mode
    powerprofilesctl set power-saver
    sudo /usr/bin/cpupower frequency-set -g powersave
}

function performance {
    # run at 120Hz
    swaymsg output eDP-1 mode '1920x1200@120.003Hz'

    # performance mode
    powerprofilesctl set performance
    sudo /usr/bin/cpupower frequency-set -g ondemand
}

export SWAYSOCK="$( ls /run/user/1000/sway-ipc.* | head -1 )"

if [[ "$adapter_status" == off-line ]]; then
    powersave
else
    performance
fi
