#!/bin/bash

recent_files="$( fasd -tfR | awk '{ print $2 }' )"

selected=($( rofi -dmenu -multi-select <<< "$recent_files" ))

[ ${#selected[@]} -eq 0 ] && exit 0

txt_files=()
others=()

for f in ${selected[@]}; do
    istext "$f"
    ret=$?

    [[ ret -eq 0 ]] && txt_files+=("$f")
    [[ ret -eq 1 ]] && others+=("$f")
done

uxterm -e "$EDITOR ${txt_files[@]}"
uxterm -e "xargs -n1 xdg-open <<< ${others[@]}"
