#!/bin/bash

if (( "$#" == 0 )); then
    sudo pacman -Syu
else
    while (( "$#" > 0 )); do
        case "$1" in
            p|path )
                source ~/.path_dirs
                shift ;;
            pac )
                sudo pacman -Syu
                shift ;;
            * )
                echo "I don't know how to do this yet!"
                shift ;;
        esac
    done
fi

