#!/bin/bash

#   Script for updating vim
#   Gets the latest source code, builds it, installs it

cd ~/vim

sudo make uninstall

git pull && git fetch

cd src
make distclean
cd ..

./configure --with-x --enable-multibyte --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=$(which ruby) --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config --enable-python3interp=dynamic --with-python3-config-dir=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu --enable-luainterp=dynamic --with-luajit --enable-cscope --enable-gui=gtk3 --with-features=huge --enable-fontset --enable-largefile --with-compiledby="yoogottamk" --enable-fail-if-missing

make

sudo make install

