#!/bin/bash

sudo apt remove --purge vim vim-runtime vim-gnome vim-tiny vim-gui-common -y
sudo dpkg -r vim

cd ~/vim
yes | rm *.deb

git pull && git fetch

cd src
make distclean
cd ..

./configure --enable-multibyte --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=/usr/bin/ruby --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-python3interp --with-python3-config-dir=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu --enable-luainterp --with-luajit --enable-cscope --enable-gui=gtk3 --with-features=huge --with-x --enable-fontset --enable-largefile --disable-netbeans --with-compiledby="yoogottamk" --enable-fail-if-missing

make

sudo checkinstall

sudo apt-mark hold vim

