#!/bin/bash

# When I connect to bluetooth headphones, the default audio device changes
# So, the controls I set up in i3 don't work [since they default to device 0]
# This script selects bluetooth headphone if present and increases it's volume
#
# The change in volume is passed as a parameter, if mute-toggle, 'm' is passed

# if change in volume is not passed, quit
[ -z "$1" ] && exit

# if change in volume is not change in volume, quit
regex='^[+-]\d+$'

if ! [[ "$1" = "m" || "$( echo "$1" | grep -P "$regex" )" ]]; then
    exit
fi

sink="$( pactl list sinks | grep "^\S" | cut -d'#' -f2 | tail -1 )"

if [[ "$1" = "m" ]]; then
    # toggle mute
    pactl set-sink-mute "$sink" toggle
else
    # change volume
    pactl set-sink-volume "$sink" "${1}%"
fi

current_volume="$( pactl list sinks | grep "^\sVolume:" | tail -1 | tr -d ' ' | cut -d'/' -f2 | cut -d'%' -f1 )"
mute="$( pactl list sinks | grep "^\sMute:" | tail -1 | tr -d ' ' | cut -d':' -f2 )"

common_flags="-h string:x-canonical-private-synchronous:volume -i /usr/share/icons/Papirus-Dark/48x48/devices/audio-speakers.svg -e"

if [[ "$mute" = "yes" ]]; then
    notify-send -u low $common_flags Volume "Volume muted"
else
    notify-send -u low -h "int:value:$current_volume" $common_flags Volume "${current_volume}%"
fi
